from datetime import UTC, datetime
import os
from typing import Any
from urllib.parse import urlparse
from uuid import NAMESPACE_URL, uuid5

from bson import ObjectId

from app.core.config import settings
from app.core.database import get_collection
from app.models.event import EventDesignStatus
from app.models.schemas.communications import CommunicationChannel
from app.models.user import User
from app.services.events import get_event_by_id
from app.services.flyers import get_flyer_by_id

ADMIN_LINKS_COLLECTION = "admin_share_links"
FLYER_DISPATCHES_COLLECTION = "flyer_dispatches"
GUESTS_COLLECTION = "guests"
STAFF_SCAN_AUDIT_COLLECTION = "staff_scan_audit"
PRODUCTION_PUBLIC_APP_URL = "https://gathervia.vercel.app"
LOCAL_PUBLIC_HOSTS = {"localhost", "127.0.0.1", "0.0.0.0", "10.0.2.2"}


def _normalize_user_id(owner: User) -> str:
    if owner.id is None:
        raise ValueError("Authenticated user must be persisted before creating links.")
    return owner.id


def _public_app_origin() -> str:
    """Return a safe frontend origin for links generated by the backend."""
    configured_origin = settings.public_app_url.rstrip("/")
    hostname = (urlparse(configured_origin).hostname or "").lower()
    running_on_render = any(
        os.getenv(name)
        for name in ("RENDER", "RENDER_SERVICE_ID", "RENDER_EXTERNAL_URL")
    )

    # A stale Render environment variable must not leak an unreachable local
    # development address into invitation, RSVP, or scanner links.
    if running_on_render and hostname in LOCAL_PUBLIC_HOSTS:
        return PRODUCTION_PUBLIC_APP_URL
    return configured_origin


def _share_url(token: str) -> str:
    return f"{_public_app_origin()}/scan/{token}"


def _invite_url(slug: str) -> str:
    return f"{_public_app_origin()}/invite/{slug}"


def _admin_rsvp_url(event_id: str) -> str:
    return f"{_public_app_origin()}/admin-rsvp/{event_id}"


def _link_token(user_id: str, event_id: str, label: str) -> str:
    return uuid5(NAMESPACE_URL, f"{user_id}:{event_id}:{label}").hex


def _serialize_admin_link(document: dict[str, Any]) -> dict[str, Any]:
    document["_id"] = str(document["_id"])
    document["owner_id"] = str(document["owner_id"])
    document["event_id"] = str(document["event_id"])
    document["enabled"] = bool(document.get("enabled", True))
    document["pin_enabled"] = bool(document.get("pin_enabled", False))
    document["pin_code"] = document.get("pin_code")
    # Do not trust the absolute URL saved when this record was created. The
    # public origin can change between local development, preview deployments,
    # and production; the stable token is the source of truth.
    document["share_url"] = _share_url(str(document["share_token"]))
    document.setdefault(
        "activity",
        {"scanned_in": 0, "scanned_out": 0, "denied": 0, "duplicate_denied": 0, "logs": []},
    )
    return document


async def _build_admin_activity(event_id: str, admin_label: str) -> dict[str, Any]:
    if not ObjectId.is_valid(event_id):
        return {"scanned_in": 0, "scanned_out": 0, "denied": 0, "duplicate_denied": 0, "logs": []}

    audit_documents = await get_collection(STAFF_SCAN_AUDIT_COLLECTION).find(
        {"event_id": ObjectId(event_id), "admin_label": admin_label}
    ).sort("timestamp", -1).to_list(length=5000)

    logs: list[dict[str, Any]] = []
    scanned_in = 0
    scanned_out = 0
    denied = 0
    duplicate_denied = 0

    for document in audit_documents:
        action = str(document.get("action", "unknown"))
        outcome = str(document.get("outcome", "allowed"))
        if action in {"scan_in", "return"} and outcome == "allowed":
            scanned_in += 1
        elif action == "scan_out" and outcome == "allowed":
            scanned_out += 1
        elif outcome == "denied":
            denied += 1
            if action == "duplicate_denied":
                duplicate_denied += 1

        logs.append(
            {
                "timestamp": document.get("timestamp"),
                "status": str(document.get("status", action)),
                "door_id": admin_label,
                "action": action,
                "outcome": outcome,
                "severity": str(document.get("severity", "info")),
                "lookup_method": str(document.get("lookup_method", "qr")),
                "reason": document.get("reason"),
                "guest_id": str(document.get("guest_id", "")),
                "guest_name": str(document.get("guest_name", "Unknown guest")),
                "guest_category": str(document.get("guest_category", "Unknown")),
            }
        )

    return {
        "scanned_in": scanned_in,
        "scanned_out": scanned_out,
        "denied": denied,
        "duplicate_denied": duplicate_denied,
        "logs": logs,
    }


async def _serialize_admin_link_with_activity(document: dict[str, Any]) -> dict[str, Any]:
    document = _serialize_admin_link(document)
    document["activity"] = await _build_admin_activity(
        document["event_id"],
        str(document.get("link_label") or "Admin"),
    )
    return document


async def create_admin_share_link(
    *,
    owner: User,
    event_id: str,
    link_label: str = "admin",
) -> dict[str, Any]:
    owner_id = _normalize_user_id(owner)
    event = await get_event_by_id(event_id)
    if event is None or event.owner_id != owner_id:
        raise ValueError("Event not found for the authenticated user.")
    if event.design_status != EventDesignStatus.PUBLISHED:
        raise ValueError("Convert the invitation in the editor before adding event admins.")

    normalized_label = link_label.strip() or "admin"
    token = _link_token(owner_id, event_id, normalized_label)
    share_url = _share_url(token)
    payload = {
        "owner_id": ObjectId(owner_id),
        "event_id": ObjectId(event_id),
        "link_label": normalized_label,
        "share_token": token,
        "share_url": share_url,
        "enabled": True,
        "pin_enabled": False,
        "pin_code": None,
        "created_at": datetime.now(UTC),
        "updated_at": datetime.now(UTC),
    }
    await get_collection(ADMIN_LINKS_COLLECTION).update_one(
        {"owner_id": ObjectId(owner_id), "event_id": ObjectId(event_id), "link_label": normalized_label},
        {"$set": payload},
        upsert=True,
    )
    document = await get_collection(ADMIN_LINKS_COLLECTION).find_one(
        {"owner_id": ObjectId(owner_id), "event_id": ObjectId(event_id), "link_label": normalized_label}
    )
    assert document is not None
    return await _serialize_admin_link_with_activity(document)


async def request_admin_share_link(*, event_id: str, admin_name: str) -> dict[str, Any]:
    event = await get_event_by_id(event_id)
    if event is None or event.owner_id is None:
        raise ValueError("Event not found.")
    if event.design_status != EventDesignStatus.PUBLISHED:
        raise ValueError("This invitation is not published yet.")

    normalized_label = admin_name.strip()
    if not normalized_label:
        raise ValueError("Admin name is required.")

    owner_id = event.owner_id
    token = _link_token(owner_id, event_id, normalized_label)
    share_url = _share_url(token)
    now = datetime.now(UTC)

    await get_collection(ADMIN_LINKS_COLLECTION).update_one(
        {"owner_id": ObjectId(owner_id), "event_id": ObjectId(event_id), "link_label": normalized_label},
        {
            "$setOnInsert": {
                "owner_id": ObjectId(owner_id),
                "event_id": ObjectId(event_id),
                "link_label": normalized_label,
                "share_token": token,
                "share_url": share_url,
                "enabled": False,
                "pin_enabled": False,
                "pin_code": None,
                "created_at": now,
            },
            "$set": {"updated_at": now},
        },
        upsert=True,
    )
    document = await get_collection(ADMIN_LINKS_COLLECTION).find_one(
        {"owner_id": ObjectId(owner_id), "event_id": ObjectId(event_id), "link_label": normalized_label}
    )
    assert document is not None
    return await _serialize_admin_link_with_activity(document)


async def get_admin_rsvp_context(event_id: str) -> dict[str, str] | None:
    event = await get_event_by_id(event_id)
    if event is None or event.design_status != EventDesignStatus.PUBLISHED:
        return None
    return {"event_id": event.id or event_id, "event_title": event.title}


async def get_event_public_links(*, owner: User, event_id: str) -> dict[str, str]:
    owner_id = _normalize_user_id(owner)
    event = await get_event_by_id(event_id)
    if event is None or event.owner_id != owner_id:
        raise ValueError("Event not found for the authenticated user.")
    if event.design_status != EventDesignStatus.PUBLISHED:
        raise ValueError("Convert the invitation in the editor before sharing event links.")
    return {
        "event_id": event.id or event_id,
        "invite_url": _invite_url(event.slug),
        "admin_rsvp_url": _admin_rsvp_url(event.id or event_id),
    }


async def list_admin_share_links(*, owner: User, event_id: str) -> list[dict[str, Any]]:
    owner_id = _normalize_user_id(owner)
    event = await get_event_by_id(event_id)
    if event is None or event.owner_id != owner_id:
        raise ValueError("Event not found for the authenticated user.")
    if event.design_status != EventDesignStatus.PUBLISHED:
        raise ValueError("Convert the invitation in the editor before opening Admins.")

    cursor = (
        get_collection(ADMIN_LINKS_COLLECTION)
        .find({"owner_id": ObjectId(owner_id), "event_id": ObjectId(event_id)})
        .sort("created_at", -1)
    )
    documents = await cursor.to_list(length=100)
    return [await _serialize_admin_link_with_activity(document) for document in documents]


async def toggle_admin_share_link(*, owner: User, link_id: str) -> dict[str, Any] | None:
    owner_id = _normalize_user_id(owner)
    if not ObjectId.is_valid(link_id):
        return None

    collection = get_collection(ADMIN_LINKS_COLLECTION)
    document = await collection.find_one({"_id": ObjectId(link_id), "owner_id": ObjectId(owner_id)})
    if document is None:
        return None

    next_enabled = not bool(document.get("enabled", True))
    await collection.update_one(
        {"_id": ObjectId(link_id), "owner_id": ObjectId(owner_id)},
        {"$set": {"enabled": next_enabled, "updated_at": datetime.now(UTC)}},
    )
    updated_document = await collection.find_one(
        {"_id": ObjectId(link_id), "owner_id": ObjectId(owner_id)}
    )
    assert updated_document is not None
    return await _serialize_admin_link_with_activity(updated_document)


async def update_admin_share_link_pin(
    *,
    owner: User,
    link_id: str,
    pin_enabled: bool,
    pin_code: str | None,
) -> dict[str, Any] | None:
    owner_id = _normalize_user_id(owner)
    if not ObjectId.is_valid(link_id):
        return None

    normalized_pin = pin_code.strip() if pin_code else None
    if pin_enabled and not normalized_pin:
        raise ValueError("PIN is required when PIN protection is enabled.")

    collection = get_collection(ADMIN_LINKS_COLLECTION)
    await collection.update_one(
        {"_id": ObjectId(link_id), "owner_id": ObjectId(owner_id)},
        {
            "$set": {
                "pin_enabled": pin_enabled,
                "pin_code": normalized_pin if pin_enabled else None,
                "updated_at": datetime.now(UTC),
            }
        },
    )
    document = await collection.find_one({"_id": ObjectId(link_id), "owner_id": ObjectId(owner_id)})
    if document is None:
        return None
    return await _serialize_admin_link_with_activity(document)


async def delete_admin_share_link(*, owner: User, link_id: str) -> bool:
    owner_id = _normalize_user_id(owner)
    if not ObjectId.is_valid(link_id):
        return False

    result = await get_collection(ADMIN_LINKS_COLLECTION).delete_one(
        {"_id": ObjectId(link_id), "owner_id": ObjectId(owner_id)}
    )
    return result.deleted_count > 0


async def get_admin_share_link_by_token(token: str) -> dict[str, Any] | None:
    document = await get_collection(ADMIN_LINKS_COLLECTION).find_one({"share_token": token})
    if document is None:
        return None
    return _serialize_admin_link(document)


async def resolve_admin_share_link(token: str, pin_code: str | None = None) -> dict[str, Any] | None:
    document = await get_admin_share_link_by_token(token)
    if document is None:
        return None
    if document.get("enabled") is False:
        return None
    if document.get("pin_enabled") and str(document.get("pin_code") or "") != str(pin_code or ""):
        return None
    return document


async def create_flyer_dispatch(
    *,
    owner: User,
    event_id: str,
    flyer_id: str,
    channel: CommunicationChannel,
    recipient_name: str,
    recipient_contact: str,
    message: str | None = None,
    subject: str | None = None,
) -> dict[str, Any]:
    owner_id = _normalize_user_id(owner)
    event = await get_event_by_id(event_id)
    if event is None or event.owner_id != owner_id:
        raise ValueError("Event not found for the authenticated user.")

    flyer = await get_flyer_by_id(flyer_id, owner_id)
    if flyer is None:
        raise ValueError("Flyer not found for the authenticated user.")

    token = _link_token(owner_id, event_id, f"{channel.value}:{flyer_id}")
    share_url = _invite_url(event.slug)
    provider_ready = bool(
        settings.email_api_key if channel == CommunicationChannel.EMAIL else settings.whatsapp_api_key
    )
    status = "queued" if provider_ready else "pending_configuration"

    payload = {
        "owner_id": ObjectId(owner_id),
        "event_id": ObjectId(event_id),
        "flyer_id": ObjectId(flyer_id),
        "channel": channel.value,
        "recipient_name": recipient_name.strip(),
        "recipient_contact": recipient_contact.strip(),
        "message": message,
        "subject": subject,
        "share_token": token,
        "share_url": share_url,
        "provider_ready": provider_ready,
        "status": status,
        "created_at": datetime.now(UTC),
        "updated_at": datetime.now(UTC),
    }
    result = await get_collection(FLYER_DISPATCHES_COLLECTION).insert_one(payload)
    document = await get_collection(FLYER_DISPATCHES_COLLECTION).find_one({"_id": result.inserted_id})
    assert document is not None
    document["_id"] = str(document["_id"])
    document["owner_id"] = str(document["owner_id"])
    document["event_id"] = str(document["event_id"])
    document["flyer_id"] = str(document["flyer_id"])
    return document
