CANVAS_WIDTH = 1080
CANVAS_HEIGHT = 1920
EDITOR_WIDTH = 320
SCALE = CANVAS_WIDTH / EDITOR_WIDTH
TOP_HEIGHT = CANVAS_HEIGHT * 2 // 3
STUB_HEIGHT = CANVAS_HEIGHT - TOP_HEIGHT
CURVE_DEPTH = 32 * SCALE
CURVE_CONTROL_FACTOR = 0.45
MIN_QR_BOTTOM_PERCENT = 38
QR_PADDING = 12 * SCALE
QR_RADIUS = 18 * SCALE
BADGE_MIN_WIDTH = 96 * SCALE
BADGE_HEIGHT = 32 * SCALE
BADGE_HORIZONTAL_PADDING = 18 * SCALE
FOOTER_BOTTOM_PERCENT = 6
FOOTER_FONT_SIZE = 13 * SCALE
DETAILS_WIDTH_PERCENT = 44
DETAILS_FONT_SIZE = 10 * SCALE
DETAILS_ICON_SIZE = 12 * SCALE
DETAILS_GAP = 6 * SCALE
SECURE_QR_FOREGROUND = "#000000"
SECURE_QR_BACKGROUND = "#ffffff"

SUPPORTED_LAYER_TYPES = frozenset(
    {"text", "image", "rect", "ellipse", "polygon", "qr", "frame", "path"}
)
