import { Modal, Pressable, StyleSheet, Text, View } from "react-native";
import { Copy, Share2, Trash2, X } from "lucide-react-native";
import { useThemeMode } from "@/context/ThemeContext";
import type { AdminShareLinkResponse } from "@/lib/types/communications";

export function AdminActionsModal({ admin, onClose, onCopy, onShare, onDelete }: { admin: AdminShareLinkResponse | null; onClose: () => void; onCopy: () => void; onShare: () => void; onDelete: () => void }) {
  const { resolvedMode } = useThemeMode();
  const light = resolvedMode === "light";
  const colors = light ? { card: "#ffffff", soft: "#f4f7f6", border: "#d5e2de", text: "#10211d", muted: "#657772" } : { card: "#0b1815", soft: "#10221e", border: "#285046", text: "#f5f8f7", muted: "#89a099" };
  const Action = ({ icon, title, hint, danger, onPress }: { icon: React.ReactNode; title: string; hint: string; danger?: boolean; onPress: () => void }) => <Pressable onPress={onPress} style={[styles.action, { backgroundColor: colors.soft, borderColor: danger ? "#6b3033" : colors.border }]}>{icon}<View><Text style={[styles.actionTitle, { color: danger ? "#e66d72" : colors.text }]}>{title}</Text><Text style={[styles.actionHint, { color: colors.muted }]}>{hint}</Text></View></Pressable>;
  return <Modal visible={Boolean(admin)} transparent animationType="fade" onRequestClose={onClose}><View style={styles.overlay}><Pressable style={StyleSheet.absoluteFill} onPress={onClose} /><View style={[styles.sheet, { backgroundColor: colors.card, borderColor: colors.border }]}><View style={styles.header}><View><Text style={[styles.title, { color: colors.text }]} numberOfLines={1}>{admin?.link_label}</Text><Text style={[styles.hint, { color: colors.muted }]}>Admin scanner actions</Text></View><Pressable onPress={onClose} style={[styles.close, { borderColor: colors.border }]}><X color={colors.muted} size={16} /></Pressable></View><Action icon={<Copy color="#4fd6be" size={18} />} title="Copy scanner link" hint="Copy this admin's personal access link" onPress={onCopy} /><Action icon={<Share2 color="#4fd6be" size={18} />} title="Share scanner link" hint="Open the native sharing options" onPress={onShare} /><Action icon={<Trash2 color="#e66d72" size={18} />} title="Delete admin" hint="Disable and permanently remove access" danger onPress={onDelete} /></View></View></Modal>;
}

const styles = StyleSheet.create({ overlay: { flex: 1, padding: 16, justifyContent: "flex-end", backgroundColor: "rgba(0,0,0,0.58)" }, sheet: { width: "100%", maxWidth: 430, alignSelf: "center", padding: 14, borderRadius: 8, borderWidth: 1, gap: 8 }, header: { minHeight: 44, marginBottom: 2, flexDirection: "row", alignItems: "center", justifyContent: "space-between" }, title: { maxWidth: 280, fontSize: 14, fontWeight: "800" }, hint: { marginTop: 2, fontSize: 9 }, close: { width: 31, height: 31, borderRadius: 16, borderWidth: 1, alignItems: "center", justifyContent: "center" }, action: { minHeight: 62, paddingHorizontal: 12, borderRadius: 8, borderWidth: 1, flexDirection: "row", alignItems: "center", gap: 11 }, actionTitle: { fontSize: 11, fontWeight: "800" }, actionHint: { marginTop: 3, fontSize: 8 } });
